### ISSUE TITLE
Study the project and update contributing,md file

### ISSUE THREAD

**Issue by masabinhok** [masabinhok/funtober#2]
Currently, the contributing.md file might not describe how a contirbutor can contibute perfectly. Study the example of spendElonMoney and all the files related and update the file with necessary changes. For example, if anybody want to add a game or fun task, the should update the array on ./src/data/funtober, create thubmnail and add on ./src/assets and import and export from there, they might want to update the App.tsx file for the route, and many more to find.

**Comment by Arsomuu** [comment]
can you assign this to me ?

**Comment by masabinhok** [comment]
Assigned!

**Comment by Arsomuu** [comment]
pull request sent
